### ISSUE TITLE
Error in common.php

### ISSUE THREAD

**Issue by nickklein95** [koter84/wpSOL#1]
Parse error: syntax error, unexpected '[', expecting ')' in /var/www/wp-content/plugins/wpsol/common.php on line 174

**Comment by koter84** [comment]
sorry....
i used a [ ] to create an array, but this is only available since PHP 5.4, i guess you are using an older version than that, which gives you this error.

i fixed this in 3dcdef4500cdcbd66c7bae047c56537b09f102f9 (v1.1.11)
