### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Anorionil** [koter84/wpSOL#4]
I get an 500 error when trying to log in. The plugin has been working correctly for the last few years. I suspect login.scouting.nl is down. But it would be nice to get a normal error instead of an internal server error.

Logs show:
read data timeout in 45 seconds, referer: <domain>/wp-login.php
End of script output before headers: wp-login.php, referer: <domain>/wp-login.php

I've just updated to Wordpress 5.6 but it was already malfunctioning right before I updated.

**Comment by koter84** [comment]
thanks for letting me know, i'll try to see what i can do about that, 500 errors aren't pretty :-(

**Comment by koter84** [comment]
i tried to reproduce the issue, and when i am able to create a timeout on the connection to login.scouting.nl (by changing it to a non-responsive url) i just get an error thrown by WordPress, so i guess they fixed it somewhere in WordPress itself..
