### ISSUE TITLE
Redirected to ?login=empty

### ISSUE THREAD

**Issue by phavekes** [koter84/wpSOL#6]
After succesfull login (I can see the openid call returning the name, email-address, etc of the user) wordpress redirect me to https://\<site\>//?login=empty . The user is not created. User creation is enabled. What is wrong, and how can I debug this?

Wordpress version 5.6

![image](https://user-images.githubusercontent.com/3096423/105360836-54a4c180-5bf9-11eb-9b25-5526359bf3e4.png)

**Comment by koter84** [comment]
i spun up my test environment so i could test the user-creation under 5.6, but i'm not seeing any problems.

often problems come from 2 (or more) plugins not working together but against each other, you could try removing all other plugins and re-adding them one-by-one or removing them one-by-one until it works.
or you could let me know which plugins you have installed, and i'll add those to my test environment to see where the problem might come from.

**Comment by phavekes** [comment]
Thank you for investigating. The problem seems to be in the theme; another theme works fine.
